---
title: "BOI_Regression"
author: "Stan West"
date: "2024-10-07"
output: pdf_document
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)

df <- readRDS("data/BOI-Assert-ADC_metadata.rds")
load("data/concrete_abstract.Rdata")
df_stim <- m_conc_abs %>%
  select(Word, level = level) %>%
  unique() %>%
  mutate(level = as.character(level))

df_stim$level[is.na(df_stim$level) ] <- "abstract"
df_stim$level <- as.factor(df_stim$level)



```


## Descriptives

```{r}
df_descrip <- df %>%
  left_join(df_stim, by = c("word" = "Word")) %>%
  select(PROLIFIC_PID, correct, duration, group, n_correct,n_incorrect, level,adc_compscore) %>%
  group_by(PROLIFIC_PID, level) %>%
  reframe(PROLIFIC_PID = PROLIFIC_PID, 
            mean_duration = mean(duration),
            perc_correct = sum(correct == "true")/sum(correct == "true" | correct == "false"),
            group = group,
            adc_compscore = adc_compscore) %>%
  unique()



df_descrip %>%
  group_by(group) %>%
  summarize(mean_dur = mean(mean_duration),
            mean_correct = mean(perc_correct))

ggplot(df_descrip, aes(x = group, y = mean_duration))+
  geom_boxplot()


ggplot(df_descrip, aes(x = group, y = perc_correct))+
  geom_boxplot()+
  facet_wrap(~Level)
  


```





## Filter only correct responses

```{r cars}

df_plot <- df_joined %>%
  select(PROLIFIC_PID, duration, perc_correct, Level, group,correct,n_correct,n_incorrect,adc_compscore) %>%
  group_by(PROLIFIC_PID, Level) %>%
  summarize(PROLIFIC_PID = PROLIFIC_PID, duration = mean(duration), perc_correct = sum(correct == "true") / sum(correct == "true" | correct == "false"), Level = Level, group = group, adc_compscore = adc_compscore) %>%
  unique()
  
  
ggplot(df_plot, aes(x = adc_compscore, y = duration, color = group))+
  geom_point() +
  facet_grid(~Level)+
  geom_smooth(method = "lm")


summary(lm(duration ~ adc_compscore, data = df_joined))

summary(lm(duration ~ adc_compscore + group + Level, data = df_joined))



```

## 

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
